### ISSUE TITLE
Tombstone this repo

### ISSUE THREAD

**Issue by kevmoo** [dart-archive/dart-protoc-plugin#144]
- [x] Put a commit that removes all content except readme w/ a pointer to the new repo localtion
- [x] Tell @kevmoo to move this repo to dart-archive

CC @mit-mit

**Comment by sigurdm** [comment]
The commit has landed.
We also need to move open issues

**Comment by mit-mit** [comment]
Issues (all except the present issue) have been moved to /protobuf

**Comment by mit-mit** [comment]
However, I think we need to get the open pull requests resolved before we move this repo: https://github.com/dart-lang/dart-protoc-plugin/pulls

**Comment by kevmoo** [comment]
I'm going to move this to `dart-archive` now, but I'm not going to hit the `archive` button – so the PRs, etc can still be modified, moved, etc
